### ISSUE TITLE
Negative energy?

### ISSUE THREAD

**Issue by IBP-0** [TheMrGong/HugBot#1]
Why? :'(

![image](https://user-images.githubusercontent.com/61919539/76763477-92c78e00-6769-11ea-9849-898e49854d12.png)

<3 HugBot though. It/She/He/They are very high on the Rep(Hug) Board in my server. 

Cheers,

**Comment by TheMrGong** [comment]
I believe I should have resolved this issue with the newest update. Any users with negative energy have been reset to 10 energy. Reopen if this continues to occur.
